# Generated by Django 5.1.7 on 2025-03-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Employee',
        ),
    ]
